// Auto-generated by data-pipeline/rig_lag.py. Do not edit by hand.
//
// One lagged regressor: production(t) = a + b x rigs(t - 9).
// Fitted on 16 observations, validated by rolling-origin backtest with
// 8 origins, refitting at each origin so there is no look-ahead.
// Bands are split-conformal from the backtest residuals. With 8 residuals
// only the 80% level is honestly supported; the outer bound is the largest
// residual observed and is labelled as such rather than dressed up as 95%.
export const RIG_LAG = {
 "lag": 9,
 "intercept": 1343.53,
 "slope": 13.346,
 "n": 16,
 "origins": 8,
 "mae": 25.3,
 "naiveMae": 36.6,
 "mase": 0.69,
 "band80": 45.2,
 "bandMax": 70.9,
 "residuals": [
  2.4,
  8.3,
  8.6,
  13.7,
  19.1,
  34.0,
  45.2,
  70.9
 ],
 "stability": {
  "preSlope": 6.843,
  "preIntercept": 1429.27,
  "preN": 10,
  "fullSlope": 13.346,
  "shiftPct": 95
 },
 "backtest": [
  {
   "month": "2025-12",
   "actual": 1477,
   "pred": 1511.0,
   "err": -34.0
  },
  {
   "month": "2026-01",
   "actual": 1488,
   "pred": 1507.1,
   "err": -19.1
  },
  {
   "month": "2026-02",
   "actual": 1420,
   "pred": 1490.9,
   "err": -70.9
  },
  {
   "month": "2026-03",
   "actual": 1449,
   "pred": 1494.2,
   "err": -45.2
  },
  {
   "month": "2026-04",
   "actual": 1520,
   "pred": 1517.6,
   "err": 2.4
  },
  {
   "month": "2026-05",
   "actual": 1554,
   "pred": 1545.7,
   "err": 8.3
  },
  {
   "month": "2026-06",
   "actual": 1583,
   "pred": 1591.6,
   "err": -8.6
  },
  {
   "month": "2026-07",
   "actual": 1546,
   "pred": 1559.7,
   "err": -13.7
  }
 ],
 "fitted": [
  {
   "month": "2025-04",
   "actual": 1522,
   "fit": 1530.4
  },
  {
   "month": "2025-05",
   "actual": 1513,
   "fit": 1530.4
  },
  {
   "month": "2025-06",
   "actual": 1543,
   "fit": 1530.4
  },
  {
   "month": "2025-07",
   "actual": 1557,
   "fit": 1490.3
  },
  {
   "month": "2025-08",
   "actual": 1529,
   "fit": 1490.3
  },
  {
   "month": "2025-09",
   "actual": 1491,
   "fit": 1503.7
  },
  {
   "month": "2025-10",
   "actual": 1496,
   "fit": 1503.7
  },
  {
   "month": "2025-11",
   "actual": 1491,
   "fit": 1477.0
  },
  {
   "month": "2025-12",
   "actual": 1477,
   "fit": 1477.0
  },
  {
   "month": "2026-01",
   "actual": 1488,
   "fit": 1490.3
  },
  {
   "month": "2026-02",
   "actual": 1420,
   "fit": 1463.6
  },
  {
   "month": "2026-03",
   "actual": 1449,
   "fit": 1490.3
  },
  {
   "month": "2026-04",
   "actual": 1520,
   "fit": 1517.0
  },
  {
   "month": "2026-05",
   "actual": 1554,
   "fit": 1543.7
  },
  {
   "month": "2026-06",
   "actual": 1583,
   "fit": 1583.8
  },
  {
   "month": "2026-07",
   "actual": 1546,
   "fit": 1557.1
  }
 ],
 "projection": [
  {
   "month": "2026-08",
   "fromMonth": "2025-11",
   "rigs": 16.0,
   "pred": 1557.1
  },
  {
   "month": "2026-09",
   "fromMonth": "2025-12",
   "rigs": 17.0,
   "pred": 1570.4
  },
  {
   "month": "2026-10",
   "fromMonth": "2026-01",
   "rigs": 15.0,
   "pred": 1543.7
  },
  {
   "month": "2026-11",
   "fromMonth": "2026-02",
   "rigs": 15.0,
   "pred": 1543.7
  },
  {
   "month": "2026-12",
   "fromMonth": "2026-03",
   "rigs": 17.0,
   "pred": 1570.4
  },
  {
   "month": "2027-01",
   "fromMonth": "2026-04",
   "rigs": 12.0,
   "pred": 1503.7
  },
  {
   "month": "2027-02",
   "fromMonth": "2026-05",
   "rigs": 17.0,
   "pred": 1570.4
  },
  {
   "month": "2027-03",
   "fromMonth": "2026-06",
   "rigs": 18.0,
   "pred": 1583.8
  },
  {
   "month": "2027-04",
   "fromMonth": "2026-07",
   "rigs": 18.0,
   "pred": 1583.8
  }
 ]
} as const;
