// Auto-generated by data-pipeline/rig_lag.py and realtime.py. Do not edit by hand.
//
// production(t) = a + b x rigs(t - 9).
//
// Two backtests are carried, and the difference between them matters.
//   `backtest`  refits at each origin but trains on today's revised figures.
//   `realtime`  rebuilds the dataset from the OPEC vintages themselves, so the
//               model sees only what a forecaster actually had on the day.
// The real-time result is the honest one and it is the weaker of the two.
export const RIG_LAG = {
 "lag": 9,
 "intercept": 1343.53,
 "slope": 13.346,
 "n": 16,
 "origins": 8,
 "mae": 25.3,
 "naiveMae": 36.6,
 "mase": 0.69,
 "band80": 45.2,
 "bandMax": 70.9,
 "residuals": [
  2.4,
  8.3,
  8.6,
  13.7,
  19.1,
  34.0,
  45.2,
  70.9
 ],
 "stability": {
  "preSlope": 6.843,
  "preIntercept": 1429.27,
  "preN": 10,
  "fullSlope": 13.346,
  "shiftPct": 95
 },
 "backtest": [
  {
   "month": "2025-12",
   "actual": 1477,
   "pred": 1511.0,
   "err": -34.0
  },
  {
   "month": "2026-01",
   "actual": 1488,
   "pred": 1507.1,
   "err": -19.1
  },
  {
   "month": "2026-02",
   "actual": 1420,
   "pred": 1490.9,
   "err": -70.9
  },
  {
   "month": "2026-03",
   "actual": 1449,
   "pred": 1494.2,
   "err": -45.2
  },
  {
   "month": "2026-04",
   "actual": 1520,
   "pred": 1517.6,
   "err": 2.4
  },
  {
   "month": "2026-05",
   "actual": 1554,
   "pred": 1545.7,
   "err": 8.3
  },
  {
   "month": "2026-06",
   "actual": 1583,
   "pred": 1591.6,
   "err": -8.6
  },
  {
   "month": "2026-07",
   "actual": 1546,
   "pred": 1559.7,
   "err": -13.7
  }
 ],
 "fitted": [
  {
   "month": "2025-04",
   "actual": 1522,
   "fit": 1530.4
  },
  {
   "month": "2025-05",
   "actual": 1513,
   "fit": 1530.4
  },
  {
   "month": "2025-06",
   "actual": 1543,
   "fit": 1530.4
  },
  {
   "month": "2025-07",
   "actual": 1557,
   "fit": 1490.3
  },
  {
   "month": "2025-08",
   "actual": 1529,
   "fit": 1490.3
  },
  {
   "month": "2025-09",
   "actual": 1491,
   "fit": 1503.7
  },
  {
   "month": "2025-10",
   "actual": 1496,
   "fit": 1503.7
  },
  {
   "month": "2025-11",
   "actual": 1491,
   "fit": 1477.0
  },
  {
   "month": "2025-12",
   "actual": 1477,
   "fit": 1477.0
  },
  {
   "month": "2026-01",
   "actual": 1488,
   "fit": 1490.3
  },
  {
   "month": "2026-02",
   "actual": 1420,
   "fit": 1463.6
  },
  {
   "month": "2026-03",
   "actual": 1449,
   "fit": 1490.3
  },
  {
   "month": "2026-04",
   "actual": 1520,
   "fit": 1517.0
  },
  {
   "month": "2026-05",
   "actual": 1554,
   "fit": 1543.7
  },
  {
   "month": "2026-06",
   "actual": 1583,
   "fit": 1583.8
  },
  {
   "month": "2026-07",
   "actual": 1546,
   "fit": 1557.1
  }
 ],
 "projection": [
  {
   "month": "2026-08",
   "fromMonth": "2025-11",
   "rigs": 16.0,
   "pred": 1557.1
  },
  {
   "month": "2026-09",
   "fromMonth": "2025-12",
   "rigs": 17.0,
   "pred": 1570.4
  },
  {
   "month": "2026-10",
   "fromMonth": "2026-01",
   "rigs": 15.0,
   "pred": 1543.7
  },
  {
   "month": "2026-11",
   "fromMonth": "2026-02",
   "rigs": 15.0,
   "pred": 1543.7
  },
  {
   "month": "2026-12",
   "fromMonth": "2026-03",
   "rigs": 17.0,
   "pred": 1570.4
  },
  {
   "month": "2027-01",
   "fromMonth": "2026-04",
   "rigs": 12.0,
   "pred": 1503.7
  },
  {
   "month": "2027-02",
   "fromMonth": "2026-05",
   "rigs": 17.0,
   "pred": 1570.4
  },
  {
   "month": "2027-03",
   "fromMonth": "2026-06",
   "rigs": 18.0,
   "pred": 1583.8
  },
  {
   "month": "2027-04",
   "fromMonth": "2026-07",
   "rigs": 18.0,
   "pred": 1583.8
  }
 ],
 "realtime": {
  "origins": 9,
  "mae": 28.0,
  "naiveMae": 33.1,
  "mase": 0.844,
  "band80": 51.0,
  "bandMax": 75.5,
  "slopeMin": -1.878,
  "slopeMax": 12.552,
  "earlyMae": 43.8,
  "lateMae": 8.2,
  "earlyN": 5,
  "lateN": 4,
  "rows": [
   {
    "vintage": "2025-11",
    "target": "2025-11",
    "pred": 1527.8,
    "actual": 1491.0,
    "err": -36.8,
    "slope": -1.878,
    "trainN": 7
   },
   {
    "vintage": "2025-12",
    "target": "2025-12",
    "pred": 1508.9,
    "actual": 1477.0,
    "err": -31.9,
    "slope": 3.643,
    "trainN": 8
   },
   {
    "vintage": "2026-01",
    "target": "2026-01",
    "pred": 1511.8,
    "actual": 1488.0,
    "err": -23.8,
    "slope": 4.0,
    "trainN": 9
   },
   {
    "vintage": "2026-02",
    "target": "2026-02",
    "pred": 1495.5,
    "actual": 1420.0,
    "err": -75.5,
    "slope": 5.576,
    "trainN": 10
   },
   {
    "vintage": "2026-03",
    "target": "2026-03",
    "pred": 1500.0,
    "actual": 1449.0,
    "err": -51.0,
    "slope": 9.506,
    "trainN": 11
   },
   {
    "vintage": "2026-04",
    "target": "2026-04",
    "pred": 1517.6,
    "actual": 1520.0,
    "err": 2.4,
    "slope": 11.709,
    "trainN": 12
   },
   {
    "vintage": "2026-05",
    "target": "2026-05",
    "pred": 1538.6,
    "actual": 1554.0,
    "err": 15.4,
    "slope": 12.552,
    "trainN": 13
   },
   {
    "vintage": "2026-06",
    "target": "2026-06",
    "pred": 1573.9,
    "actual": 1583.0,
    "err": 9.1,
    "slope": 11.998,
    "trainN": 14
   },
   {
    "vintage": "2026-07",
    "target": "2026-07",
    "pred": 1551.7,
    "actual": 1546.0,
    "err": -5.7,
    "slope": 12.112,
    "trainN": 15
   }
  ]
 }
} as const;
